import 
{ 
    Message,
    Form,
    FormItem,
    Input,
    Button,
    Tooltip,
    Container,
    Header,
    Aside,
    Main,
    Avatar,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Menu,
    MenuItem,
    MenuItemGroup,
    Submenu,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Table,
    TableColumn,
    Pagination,
    Row,
    Col,
    Tag,
    Checkbox,
    Select,
    Option,
    CheckboxGroup,
    MessageBox,
    Dialog,
    Image,
    Upload
} from "element-ui";
import Vue from 'vue'

Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Button)
Vue.use(Tooltip)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tag)
Vue.use(Checkbox)
Vue.use(Select)
Vue.use(Option)
Vue.use(CheckboxGroup)
Vue.use(Dialog)
Vue.use(Image)
Vue.use(Upload)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm